version: "3"

services:
    app:
        build:
            context: ./back/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - backend
    db:
        image: postgres:11
        volumes:
            - ./db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=docker
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=s3cr3t
        networks: 
            - backend
    # front:
    #     container_name: vuejs-front
    #     image: node:10-alpine
    #     working_dir: /home/myproject/front
    #     volumes:
    #         - ./front:/home/myproject/front
    #     ports:
    #         - "8081:8081"
    #     command: ["yarn", "serve"]
    adminer:
      image: 'adminer:latest'
      ports:
          - '8081:8080'
          
networks:
    backend:
