version: "3"

services:
    app:
        build:
            context: ./back/
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: unless-stopped
        depends_on:
            - db
        environment:
            REDIS_URL: redis:6379
        networks:
            - backend

    db:
        image: postgres:11
        volumes:
            - ./db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=docker
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=s3cr3t
        networks: 
            - backend

          
networks:
    backend:
